{
 "title": "TIBCO EMS",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Server stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "target": "TIBCO.DEV.EMS.localhost.server.uptime"
    }
   ]
  },
  {
   "title": "EMS state",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "target": "TIBCO.DEV.EMS.localhost.state" }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(TIBCO.DEV.EMS.localhost.connections.admin_connection_count, 'Admin connections')"
    },
    {
     "target": "alias(TIBCO.DEV.EMS.localhost.connections.client_connection_count, 'Client connections')"
    },
    {
     "target": "alias(TIBCO.DEV.EMS.localhost.connections.connection_count, 'Total connections count')"
    }
   ]
  },
  {
   "title": "Destinations count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(TIBCO.DEV.EMS.localhost.server.queue_count, 'Queue count')"
    },
    {
     "target": "alias(TIBCO.DEV.EMS.localhost.server.topic_count, 'Topic count')"
    }
   ]
  },
  {
   "title": "Consumers and producers",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(TIBCO.DEV.EMS.localhost.server.consumer_count, 'Consumer count')"
    },
    {
     "target": "alias(TIBCO.DEV.EMS.localhost.server.producer_count, 'Producer count')"
    },
    {
     "target": "alias(TIBCO.DEV.EMS.localhost.server.durable_count, 'Durable count')"
    }
   ]
  },
  {
   "title": "Server response",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(TIBCO.DEV.EMS.localhost.connections.server_response_time_ms, 'Server response time [ms]')"
    }
   ]
  },
  { "title": "Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Total number of messages",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(TIBCO.DEV.EMS.localhost.performance.msg_count_total_in, 'INPUT')"
    },
    {
     "target": "alias(TIBCO.DEV.EMS.localhost.performance.msg_count_total_out, 'OUTPUT')"
    }
   ]
  },
  {
   "title": "Pending messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "alias(TIBCO.DEV.EMS.localhost.server.pending_msg_count, 'Pending message count')"
    },
    {
     "target": "alias(TIBCO.DEV.EMS.localhost.server.pending_msg_size, 'Pending message size [bytes]')"
    }
   ]
  },
  {
   "title": "Message memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "alias(TIBCO.DEV.EMS.localhost.server.msg_mem, 'Message memory [bytes]')"
    },
    {
     "target": "alias(TIBCO.DEV.EMS.localhost.server.msg_mem_pooled, 'Pooled message memory [bytes]')"
    }
   ]
  },
  {
   "title": "Inbound messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(TIBCO.DEV.EMS.localhost.performance.msg_count_in, 'Message count [msg/s]')"
    },
    {
     "target": "alias(TIBCO.DEV.EMS.localhost.performance.msg_size_in, 'Message rate [bytes/s]')"
    }
   ]
  },
  {
   "title": "Outbound messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(TIBCO.DEV.EMS.localhost.performance.msg_count_out, 'Message count  [msg/s]')"
    },
    {
     "target": "alias(TIBCO.DEV.EMS.localhost.performance.msg_size_out, 'Message rate [byte/s]')"
    }
   ]
  },
  { "title": "Store", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Disk operations rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "alias(TIBCO.DEV.EMS.localhost.store.read_rate, 'Read rate [bytes/s]')"
    },
    {
     "target": "alias(TIBCO.DEV.EMS.localhost.store.write_rate, 'Write rate [bytes/s]')"
    }
   ]
  },
  {
   "title": "Operations per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "alias(TIBCO.DEV.EMS.localhost.store.read_operations_rate, 'Read operations [ops/s]')"
    },
    {
     "target": "alias(TIBCO.DEV.EMS.localhost.store.write_operations_rate, 'Write operations [ops/s]')"
    }
   ]
  },
  {
   "title": "Store size in use",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "alias(TIBCO.DEV.EMS.localhost.store.async_db_size, 'ASYNC DB Size [bytes]')"
    },
    {
     "target": "alias(TIBCO.DEV.EMS.localhost.store.sync_db_size, 'SYNC DB Size [bytes]')"
    }
   ]
  }
 ]
}